import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import express from 'express';

test('Danang feed, owner access and automatic delivery', async t => {
  const dir = await mkdtemp(join(tmpdir(), 'cashalot-news-'));
  process.env.STORE_PATH = join(dir, 'store.json'); delete process.env.DATABASE_URL;
  process.env.ADMIN_WEB_KEY = 'news-test-owner';
  const { NEWS_SOURCES, parseNewsFeed, relevantToDanang, duplicateNews, newsState, visibleNews, deliveryCandidate, syncNews, publicNewsPost, newsTelegramText } = await import('../server/src/news.ts');
  const { ingestTelegramNews } = await import('../server/src/newsTelegram.ts');
  const { publicTelegramUsername, parsePublicTelegramPage, fetchPublicTelegramPage, pollPublicTelegramSource } = await import('../server/src/newsPublicTelegram.ts');
  const { readStore, mutateStore } = await import('../server/src/store.ts');
  const { createApiRouter } = await import('../server/src/routes.ts');
  const now = new Date('2026-10-04T05:00:00Z');
  const item = (title = 'В Дананге открылся новый музей', link = 'https://www.atorus.ru/danang-museum', date = now.toUTCString()) => `<item><title><![CDATA[${title}]]></title><description><![CDATA[Музей в Дананге принимает посетителей каждый день. <script>alert(1)</script>]]></description><link>${link}</link><pubDate>${date}</pubDate></item>`;
  const rss = (items: string) => `<rss><channel>${items}</channel></rss>`;
  const post = parseNewsFeed(rss(item()), NEWS_SOURCES[0], now)[0];
  await t.test('only fresh Danang news or national entry rules, and no XML entities or unsafe links', () => {
    assert.equal(post.category, 'places'); assert.equal(post.source, 'АТОР'); assert.doesNotMatch(post.summary, /script|alert/);
    assert.ok((post.title + ' ' + post.summary).trim().split(/\s+/).length <= 24);
    assert.equal(relevantToDanang('Открылось кафе в Нячанге', 'Отпуск во Вьетнаме'), false);
    assert.equal(relevantToDanang('Вьетнам изменил правила въезда', ''), true);
    assert.equal(relevantToDanang('Новые отели Вьетнама', ''), false);
    assert.equal(parseNewsFeed(rss(item('Дананг', 'javascript:alert(1)')), NEWS_SOURCES[0], now).length, 0);
    assert.equal(parseNewsFeed(rss(item('Дананг', 'https://evil.invalid/danang')), NEWS_SOURCES[0], now).length, 0);
    assert.equal(parseNewsFeed(rss(item('Дананг', 'https://www.atorus.ru/a', 'bad')), NEWS_SOURCES[0], now).length, 0);
    assert.equal(parseNewsFeed(rss(item('Дананг', 'https://www.atorus.ru/a', 'Mon, 01 Jan 2024 00:00:00 GMT')), NEWS_SOURCES[0], now).length, 0);
    assert.equal(parseNewsFeed(rss(item('Дананг', 'https://www.atorus.ru/a', 'Mon, 05 Oct 2026 00:00:00 GMT')), NEWS_SOURCES[0], now).length, 0);
    assert.throws(() => parseNewsFeed('<!DOCTYPE a [<!ENTITY x "boom">]>' + rss(item()), NEWS_SOURCES[0], now));
    assert.throws(() => parseNewsFeed('<html>blocked</html>', NEWS_SOURCES[0], now));
    assert.equal(duplicateNews(post, { ...post, id: 'other', url: 'https://tourdom.ru/other' }), true);
  });
  await t.test('expired and hidden posts stay out of public feed and delivery; quiet hours and caps', () => {
    const s = newsState({ config: {} } as any);
    s.posts = [post]; s.channel = { id: -100123, title: 'Твой Вьетнам', connectedAt: '2026-10-04T04:00:00Z' };
    assert.equal(deliveryCandidate(s, now)?.id, post.id);
    s.posts = [{ ...post, hidden: true }, { ...post, id: 'expired', expiresAt: '2026-10-03T00:00:00Z' }];
    assert.equal(visibleNews(s, now).length, 0); assert.equal(deliveryCandidate(s, now), undefined);
    s.posts = [post]; assert.equal(deliveryCandidate(s, new Date('2026-10-04T15:00:00Z')), undefined);
    s.lastSendAt = '2026-10-04T04:00:00Z'; assert.equal(deliveryCandidate(s, now), undefined); delete s.lastSendAt;
    s.channel.connectedAt = '2026-10-04T06:00:00Z'; assert.equal(deliveryCandidate(s, now), undefined);
    s.channel.connectedAt = '2026-10-04T04:00:00Z';
    s.posts.push(...[1, 2, 3].map(i => ({ ...post, id: `sent-${i}`, delivery: { state: 'sent' as const, at: '2026-10-04T01:00:00Z', chatId: -100123 } })));
    assert.equal(deliveryCandidate(s, now), undefined);
  });
  const actualFetch = globalThis.fetch; let telegramCalls = 0; let feedCalls = 0; let failSend = false;
  const tgPage = (items: string, before = '') => `<div class="tgme_channel_info_header_title"><span>Город у моря</span></div><div class="tgme_channel_info_header_username"><a>@danang_news</a></div><section class="tgme_channel_history">${items}${before ? `<a class="tme_messages_more" data-before="${before}"></a>` : ''}</section>`;
  const tgItem = (id: number, text = 'Новое кафе у моря<br><br>Кофе &amp; завтрак.', date = now.toISOString()) => `<div class="tgme_widget_message" data-post="danang_news/${id}"><div class="tgme_widget_message_text"><b>${text}</b></div><a class="tgme_widget_message_date"><time datetime="${date}"></time></a></div>`;
  let tgHtml = tgPage(tgItem(5)); let publicFetches = 0; let publicFailure = false; let olderHtml = '';
  t.mock.method(globalThis, 'fetch', async (url: any, options: any) => {
    if (String(url).startsWith('https://t.me/s/danang_news')) {
      publicFetches++; assert.equal(options.redirect, 'error'); assert.equal(options.headers.cookie, undefined);
      if (publicFailure) return new Response('', { status: 429 });
      return new Response(String(url).includes('?before=') ? olderHtml : tgHtml, { headers: { 'content-type': 'text/html' } });
    }
    if (String(url).startsWith('https://www.atorus.ru/')) { feedCalls++; return new Response(rss(item())); }
    if (String(url).includes('/sendMessage')) { telegramCalls++; assert.equal(JSON.parse(options.body).chat_id, -100123); if (failSend) throw Error('timeout'); return Response.json({ ok: true, result: { message_id: 77 } }); }
    throw Error('Unexpected upstream request');
  });
  await t.test('concurrent refreshes deduplicate; persisted claims prevent duplicate channel sends', async () => {
    await mutateStore(s => { const n = newsState(s); n.sources = ['ator']; n.channel = { id: -100123, title: 'Твой Вьетнам', connectedAt: '2026-10-04T04:00:00Z' }; });
    await Promise.all([syncNews('123:test', now), syncNews('123:test', now)]);
    assert.equal(feedCalls, 1); assert.equal(telegramCalls, 1);
    let n = newsState(await readStore()); assert.equal(n.posts.length, 1); assert.equal(n.posts[0].delivery?.state, 'sent');
    await syncNews('123:test', new Date('2026-10-04T08:00:00Z')); assert.equal(telegramCalls, 1);
    await mutateStore(s => { const n = newsState(s); delete n.posts[0].delivery; delete n.lastSendAt; }); failSend = true;
    await syncNews('123:test', now); assert.equal(telegramCalls, 2);
    n = newsState(await readStore()); assert.equal(n.posts[0].delivery?.state, 'uncertain');
    await syncNews('123:test', new Date('2026-10-04T09:00:00Z')); assert.equal(telegramCalls, 2);
    await mutateStore(s => { newsState(s).enabled = false; }); const before = feedCalls; await syncNews('123:test', now); assert.equal(feedCalls, before);
  });
  const app = express(); app.use(express.json()); app.use('/api', createApiRouter({ botToken: '123:test' }));
  const server = app.listen(0, '127.0.0.1'); await new Promise<void>(r => server.once('listening', r));
  const base = `http://127.0.0.1:${(server.address() as any).port}/api`;
  const req = async (path: string, body?: any, owner = true) => { const r = await actualFetch(base + path, { method: body === undefined ? 'GET' : 'POST', headers: { 'content-type': 'application/json', ...(owner ? { 'x-admin-key': 'news-test-owner' } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) }); return { status: r.status, data: await r.json() as any }; };
  t.after(async () => { await new Promise<void>(r => server.close(() => r())); await rm(dir, { recursive: true, force: true }); });
  await t.test('only owners manage sources and posts; public responses omit internal delivery state', async () => {
    assert.equal((await req('/admin/news', undefined, false)).status, 401);
    assert.equal((await req('/admin/news/visibility', { id: post.id, hidden: true }, false)).status, 401);
    assert.equal((await req('/admin/news/settings', { enabled: true, sources: ['http://127.0.0.1'] })).status, 400);
    assert.equal((await req('/admin/news/post', { title: 'Акция в Дананге', category: 'offers' })).status, 400);
    assert.equal((await req('/admin/news/post', { title: 'Место в Дананге', category: 'places', url: 'javascript:alert(1)' })).status, 400);
    const created = await req('/admin/news/post', { title: 'Место в Дананге', category: 'places', summary: 'Собственный обзор' }); assert.equal(created.status, 200);
    let pub = await req('/news', undefined, false); assert.equal(pub.status, 200); assert.ok(pub.data.posts.every((p: any) => !('delivery' in p) && !('hidden' in p)));
    await req('/admin/news/visibility', { id: created.data.id, hidden: true }); pub = await req('/news', undefined, false); assert.ok(!pub.data.posts.some((p: any) => p.id === created.data.id));
    await req('/admin/news/visibility', { id: created.data.id, hidden: false }); pub = await req('/news', undefined, false); assert.ok(pub.data.posts.some((p: any) => p.id === created.data.id));
    assert.equal((await req('/admin/news')).data.enabled, false);
  });
  await t.test('connected Telegram channels only; no echoes, protected content, duplicates or public attribution', async () => {
    await mutateStore(s => { const n = newsState(s); n.enabled = true; n.telegramSources = [{ id: -100456, title: 'Редакция Дананга', username: 'danang_editor', connectedAt: '2026-10-04T04:00:00Z' }]; });
    const msg = { chat: { id: -100456, type: 'channel' }, message_id: 11, date: +now / 1000, text: 'Новое кафе у моря\n\nВ Дананге открылось кафе с видом на пляж.' };
    assert.equal(await ingestTelegramNews({ ...msg, chat: { id: 123, type: 'private' } }, now), false);
    assert.equal(await ingestTelegramNews({ ...msg, chat: { id: -100999, type: 'channel' } }, now), false);
    await ingestTelegramNews({ ...msg, has_protected_content: true }, now);
    assert.equal(newsState(await readStore()).posts.filter(p => p.sourceKind === 'telegram').length, 0);
    await ingestTelegramNews(msg, now); await ingestTelegramNews(msg, now);
    const posts = newsState(await readStore()).posts.filter(p => p.sourceKind === 'telegram'); assert.equal(posts.length, 1);
    const p = posts[0]; assert.equal(p.category, 'places'); assert.equal(p.summary, 'В Дананге открылось кафе с видом на пляж.');
    const pub = publicNewsPost(p); assert.equal(pub.source, ''); assert.equal(pub.url, ''); assert.ok(!('sourceId' in pub));
    assert.doesNotMatch(newsTelegramText(p), /Редакция|danang_editor|Читать в источнике/);
    assert.match(newsTelegramText(post), /АТОР|Читать в источнике/);
    const api = await req('/news', undefined, false); assert.ok(api.data.posts.some((x: any) => x.id === p.id && x.source === '' && !x.url));
    await mutateStore(s => { newsState(s).channel = { id: -100456, title: 'Own channel', connectedAt: now.toISOString() }; });
    assert.equal(await ingestTelegramNews({ ...msg, message_id: 12 }, now), false);
    await mutateStore(s => { delete newsState(s).channel; newsState(s).enabled = false; });
    await ingestTelegramNews({ ...msg, message_id: 13, text: 'Другая новость Дананга' }, now);
    assert.equal(newsState(await readStore()).posts.filter(p => p.sourceKind === 'telegram').length, 1);
    assert.equal((await req('/admin/news/telegram-source', { channel: '@example' }, false)).status, 401);
    assert.equal((await req('/admin/news/telegram-source', { remove: true, id: -100456 })).status, 200);
    assert.equal(newsState(await readStore()).telegramSources?.length, 0);
    assert.equal(await ingestTelegramNews(msg, now), false);
  });
  await t.test('public Telegram HTML: strict URLs, identity, message dates, safe nested text and media cursors', async () => {
    assert.equal(publicTelegramUsername('https://t.me/s/DaNang_News'), 'danang_news');
    assert.equal(publicTelegramUsername('@DaNang_News'), 'danang_news');
    for (const bad of ['https://evil.test/danang_news', 'http://t.me/danang_news', 'https://t.me@127.0.0.1/danang_news', 'https://t.me/+secret', 'https://t.me/c/123/456', 'https://t.me/danang_news?x=1', 'https://t.me/s/../../admin']) assert.equal(publicTelegramUsername(bad), null);
    const parsed = parsePublicTelegramPage(tgPage(tgItem(6, 'Кафе &amp; море<br><br><i>Открытие</i><script>secret()</script>') + '<div class="tgme_widget_message" data-post="danang_news/7"></div>'), 'danang_news');
    assert.deepEqual(parsed.ids, [6,7]); assert.equal(parsed.messages.length, 1); assert.equal(parsed.messages[0].text, 'Кафе & море\n\nОткрытие');
    assert.throws(() => parsePublicTelegramPage('<html>Login required</html>', 'danang_news'));
    assert.throws(() => parsePublicTelegramPage(tgHtml.replace('@danang_news', '@other'), 'danang_news'));
    const before = publicFetches; await assert.rejects(fetchPublicTelegramPage('../admin')); assert.equal(publicFetches, before);
    publicFailure = true; await assert.rejects(fetchPublicTelegramPage('danang_news'), /частоту/); publicFailure = false;
  });
  await t.test('public channels connect without Bot API, skip old posts and import new posts once with persistent errors', async () => {
    assert.equal((await req('/admin/news/public-telegram-source', { channel: '@danang_news' }, false)).status, 401);
    const fetched = publicFetches;
    assert.equal((await req('/admin/news/public-telegram-source', { channel: 'https://127.0.0.1/' })).status, 400); assert.equal(publicFetches, fetched);
    assert.equal((await req('/admin/news/public-telegram-source', { channel: '@danang_news' })).status, 200);
    let n = newsState(await readStore()); let source = n.publicTelegramSources![0]; assert.equal(source.lastMessageId, 5);
    assert.equal(n.posts.filter(p => p.sourceId === 'telegram:public:danang_news').length, 0);
    await req('/admin/news/public-telegram-source', { channel: 'https://t.me/DaNang_News' });
    assert.equal(newsState(await readStore()).publicTelegramSources?.length, 1);
    await mutateStore(s => { const n = newsState(s); n.enabled = true; n.sources = []; n.publicTelegramSources![0].connectedAt = '2026-10-04T04:00:00Z'; });
    tgHtml = tgPage(tgItem(6));
    await syncNews('', now); await syncNews('', now);
    n = newsState(await readStore()); source = n.publicTelegramSources![0];
    assert.equal(source.lastMessageId, 6); assert.equal(n.posts.filter(p => p.sourceId === 'telegram:public:danang_news').length, 1);
    publicFailure = true; await syncNews('', now); n = newsState(await readStore()); assert.match(n.publicTelegramSources![0].error!, /частоту/); assert.equal(n.publicTelegramSources![0].lastMessageId, 6); publicFailure = false;
    tgHtml = tgPage(tgItem(9), '9'); olderHtml = tgPage(tgItem(8, 'Фестиваль Дананга') + tgItem(6));
    const polled = await pollPublicTelegramSource(source, now); assert.deepEqual(polled.posts.map(p => p.title), ['Новое кафе у моря', 'Фестиваль Дананга']); assert.equal(polled.lastMessageId, 9);
    olderHtml = tgPage(tgItem(8), '9'); await assert.rejects(pollPublicTelegramSource(source, now), /Слишком много/);
    await mutateStore(s => { newsState(s).channel = { id: -100999, title: 'Destination', url: 'https://t.me/danang_news', connectedAt: now.toISOString() }; });
    assert.equal((await req('/admin/news/public-telegram-source', { channel: '@danang_news' })).status, 400);
    await req('/admin/news/public-telegram-source', { remove: true, id: source.id });
    assert.equal(newsState(await readStore()).publicTelegramSources?.length, 0);
  });
});
