import express from 'express';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
const scratch = await mkdtemp(join(tmpdir(), 'cashalot-news-preview-'));
process.env.STORE_PATH = join(scratch, 'store.json');
process.env.ADMIN_WEB_KEY = 'local-news-preview';
delete process.env.DATABASE_URL;
delete process.env.NEWS_ENABLED;
delete process.env.RAILWAY_SERVICE_ID;
const { createApiRouter } = await import('../server/src/routes.ts');
const { syncNews } = await import('../server/src/news.ts');
const app = express(); app.use(express.json());
app.use('/api', createApiRouter({ botToken: '123:local-news-preview' }));
app.use(express.static(resolve('server/public')));
app.use(express.static(resolve('webapp/dist'), { index: false, maxAge: 0 }));
app.get('/admin', (_req, res) => res.sendFile(resolve('webapp/dist/admin.html')));
app.get('*', (_req, res) => res.sendFile(resolve('webapp/dist/index.html')));
app.listen(5190, '127.0.0.1', () => console.log('News preview: http://127.0.0.1:5190/?demo=1&section=news ; owner key: local-news-preview'));
await syncNews('');
