import React, { useEffect, useState } from 'react';
import { referralApi } from '../lib/referrals';
import { newsLabels, type NewsItem } from '../tabs/NewsTab';
import './owner-news.css';
type NewsAdmin = { weather?: { enabled: boolean; error?: string; lastPin?: { messageId: number }; jobs: { day: string; state: string; pinned?: boolean }[] }; publicTelegramSources?: { id: string; title: string; username: string; lastReceivedAt?: string; lastCheckedAt?: string; error?: string }[]; telegramSources?: { id: number; title: string; username?: string; lastReceivedAt?: string }[]; enabled: boolean; sources: string[]; posts: NewsItem[]; checkedAt?: string; channel?: { title: string; id: string | number; url?: string }; sourcesCatalog: { id: string; name: string; language: string }[]; sourceStatus: Record<string, { checkedAt: string; count?: number; error?: string }> };
const emptyPost = { title: '', summary: '', category: 'places', url: '', mapUrl: '', expiresAt: '' };
export default function OwnerNews({ token }: { token: string }) {
  const [data, setData] = useState<NewsAdmin | null>(null); const [enabled, setEnabled] = useState(true); const [sources, setSources] = useState<string[]>([]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [sourceChannel, setSourceChannel] = useState(''); const [sourceMode, setSourceMode] = useState('public');
  const [channel, setChannel] = useState(''); const [view, setView] = useState('all'); const [compose, setCompose] = useState(false); const [draft, setDraft] = useState(emptyPost);
  const load = async () => { const d = await referralApi<NewsAdmin>(token, '/admin/news'); setData(d); setEnabled(d.enabled); setSources(d.sources); };
  useEffect(() => { setBusy(true); load().catch(e => setError(e.message)).finally(() => setBusy(false)); }, [token]);
  async function action(path: string, body: unknown, message: string) {
    if (busy) return false; setBusy(true); setError(''); setNotice('');
    try { await referralApi(token, `/admin/news/${path}`, body); await load(); setNotice(message); return true; }
    catch (e: any) { setError(e.message); return false; } finally { setBusy(false); }
  }
  const posts = (data?.posts || []).filter(p => view === 'all' || (view === 'hidden' ? p.hidden : !p.hidden));
  return <div className="on-news">
    <section className="card"><div className="on-heading"><div><h2>Твой Вьетнам</h2><p className="vx-muted">Новости Дананга для туристов и жителей города</p></div><button className="btn" disabled={busy || !data?.enabled} onClick={() => action('refresh', {}, 'Источники проверены. Результат — ниже.')}>{busy ? 'Подождите…' : 'Проверить источники'}</button></div>
      {error && <p role="alert" className="on-error">{error}</p>}{notice && <p role="status">{notice}</p>}
      <div className="on-settings"><div><h3>Автоматическая лента</h3><label className="on-check"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} disabled={busy}/>Публиковать новые материалы автоматически</label><p className="vx-muted">Проверка каждые 15 минут. Отбираются материалы о Дананге и важные изменения правил въезда во Вьетнам.</p>
        {data?.sourcesCatalog.map(s => <div className="on-source" key={s.id}><label className="on-check"><input type="checkbox" disabled={busy} checked={sources.includes(s.id)} onChange={e => setSources(old => e.target.checked ? [...old, s.id] : old.filter(id => id !== s.id))}/>{s.name}{s.language === 'vi' ? ' · перевод на русский' : s.language === 'en' ? ' · на английском, без перевода' : ''}</label><small>{data.sourceStatus[s.id]?.error || (data.sourceStatus[s.id] ? `Проверено ${new Date(data.sourceStatus[s.id].checkedAt).toLocaleString('ru-RU')} · подходит ${data.sourceStatus[s.id].count || 0}` : 'Ещё не проверен')}</small></div>)}
        <button className="btn" disabled={busy || !data} onClick={() => action('settings', { enabled, sources }, 'Настройки ленты сохранены.')}>Сохранить настройки</button></div>
        <div><h3>Telegram-канал</h3>{data?.channel ? <p>Подключён: <strong>{data.channel.title}</strong><br/><small>{data.channel.url || data.channel.id}</small></p> : <p className="vx-muted">Добавьте тестового бота администратором новостного канала с правом публикации сообщений.</p>}<label>Канал<input className="input vx-in" value={channel} onChange={e => setChannel(e.target.value)} placeholder="@имя_канала или ID" disabled={busy}/></label><div className="on-actions"><button className="btn" disabled={busy || !channel.trim()} onClick={() => action('channel', { channel }, 'Канал подключён. В него будут попадать новые публикации.')}>Подключить</button>{data?.channel && <button className="btn" disabled={busy} onClick={() => action('channel', { disconnect: true }, 'Публикация в канал отключена.')}>Отключить</button>}</div><p className="vx-muted">До 3 новостей в день, с 08:00 до 21:00 по Данангу. Интервал — от 2 часов. Материалы, добавленные до подключения канала, не отправляются.</p></div></div>
    </section>
    <section className="card"><h3>Погода каждое утро</h3><p className="vx-muted">В 08:00 по Данангу: прогноз на утро, день и вечер. Новый прогноз закрепляется, вчерашний снимается с закрепления. Остальные закрепы остаются. Погода не занимает лимит новостей.</p><label className="on-check"><input type="checkbox" checked={data?.weather?.enabled || false} disabled={busy} onChange={e => action('weather', { enabled: e.target.checked }, 'Настройки погоды сохранены.')}/>Публиковать и закреплять прогноз</label><p className="vx-muted">Боту нужны права публикации и редактирования сообщений. Источник прогноза — MET Norway.</p>{data?.weather?.error && <p role="status" className="on-error">{data.weather.error}</p>}<p className="vx-muted">Вьетнамские материалы переводятся автоматически. При ошибке или исчерпании бесплатного лимита переводчика новость ждёт перевода и не публикуется на вьетнамском.</p></section><section className="card"><h3>Telegram-источники</h3><p className="vx-muted">Вставьте ссылку на публичный канал о Дананге. Добавлять нашего бота туда не нужно. Проверка новых постов — каждые 15 минут. Импортируются текст, фото, видео и альбомы до 10 вложений. Для публичных каналов — только медиа, доступные в веб-просмотре Telegram. Фото до 10 МБ, видео до 50 МБ; если бот добавлен в источник, просмотр видео в приложении ограничен 20 МБ. Старые посты при подключении пропускаются. Название и ссылка источника видны только владельцу.</p>
      <label className="on-sourceMode">Способ подключения<select className="input vx-in" value={sourceMode} onChange={e => setSourceMode(e.target.value)} disabled={busy}><option value="public">По ссылке, без бота</option><option value="bot">Через бота в канале</option></select></label>
      {sourceMode === 'bot' && <p className="vx-muted">Для этого способа сначала добавьте бота приложения в канал-источник.</p>}
      <form className="on-sourceForm" onSubmit={async e => { e.preventDefault(); if (await action(sourceMode === 'public' ? 'public-telegram-source' : 'telegram-source', { channel: sourceChannel }, 'Источник подключён. Ожидаем новые публикации.')) setSourceChannel(''); }}><label>Канал-источник<input className="input vx-in" value={sourceChannel} onChange={e => setSourceChannel(e.target.value)} placeholder={sourceMode === 'public' ? '@канал или https://t.me/канал' : '@канал или ID'} required disabled={busy}/></label><button className="btn" disabled={busy || !sourceChannel.trim()} type="submit">Добавить источник</button></form>
      {(data?.telegramSources || []).map(s => <div className="on-source" key={s.id}><strong>{s.title}</strong> {s.username && <span>@{s.username}</span>}<small>{s.lastReceivedAt ? `Последний пост: ${new Date(s.lastReceivedAt).toLocaleString('ru-RU')}` : 'Ожидаем первый пост после подключения'}</small><button className="btn" disabled={busy} onClick={() => action('telegram-source', { remove: true, id: s.id }, 'Источник отключён. Уже добавленные публикации сохранены.')}>Отключить источник</button></div>)}
      {(data?.publicTelegramSources || []).map(s => <div className="on-source" key={s.id}><strong>{s.title}</strong> <span>@{s.username}</span><small>По публичной ссылке · {s.lastCheckedAt ? `Проверено ${new Date(s.lastCheckedAt).toLocaleString('ru-RU')}` : 'Ожидаем проверку'}</small>{s.error ? <p role="status" className="on-error">{s.error}</p> : <small>{s.lastReceivedAt ? `Последний импорт: ${new Date(s.lastReceivedAt).toLocaleString('ru-RU')}` : 'Ожидаем новые посты после подключения'}</small>}<button className="btn" disabled={busy} onClick={() => action('public-telegram-source', { remove: true, id: s.id }, 'Источник отключён. Уже добавленные публикации сохранены.')}>Отключить источник</button></div>)}
      {!data?.telegramSources?.length && !data?.publicTelegramSources?.length && <p className="vx-muted">Каналы пока не выбраны.</p>}
    </section>
    <section className="card"><div className="on-heading"><h3>Публикации · {data?.posts.length || 0}</h3><button className="btn" onClick={() => setCompose(!compose)}>{compose ? 'Закрыть редактор' : 'Своя публикация'}</button></div>
      {compose && <form className="on-compose" onSubmit={async e => { e.preventDefault(); const ok = await action('post', { ...draft, expiresAt: draft.expiresAt ? new Date(draft.expiresAt).toISOString() : '' }, 'Публикация появилась в приложении. Отправка в канал — по расписанию.'); if (ok) { setDraft(emptyPost); setCompose(false); } }}><label>Заголовок<input className="input vx-in" required minLength={5} maxLength={160} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })}/></label><label>Текст<textarea className="input vx-in" rows={5} maxLength={1600} value={draft.summary} onChange={e => setDraft({ ...draft, summary: e.target.value })}/></label><div className="on-settings"><label>Рубрика<select className="input vx-in" value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })}>{Object.entries(newsLabels).filter(([k]) => k !== 'all').map(([k, label]) => <option key={k} value={k}>{label}</option>)}</select></label><label>Действует до (время вашего устройства)<input className="input vx-in" type="datetime-local" required={draft.category === 'offers'} value={draft.expiresAt} onChange={e => setDraft({ ...draft, expiresAt: e.target.value })}/></label><label>Ссылка на подробности<input className="input vx-in" type="url" placeholder="https://…" value={draft.url} onChange={e => setDraft({ ...draft, url: e.target.value })}/></label><label>Ссылка на карту<input className="input vx-in" type="url" placeholder="https://…" value={draft.mapUrl} onChange={e => setDraft({ ...draft, mapUrl: e.target.value })}/></label></div><button className="btn" disabled={busy} type="submit">Опубликовать</button></form>}
      <div className="on-actions">{[['all','Все'],['visible','В ленте'],['hidden','Скрытые']].map(([k,l]) => <button type="button" key={k} className="btn" aria-pressed={view === k} onClick={() => setView(k)}>{l}</button>)}</div>
      <div className="on-posts">{posts.map(p => <article key={p.id} className="on-post"><div className="on-meta">{newsLabels[p.category]} · {p.source} · {new Date(p.publishedAt).toLocaleDateString('ru-RU')}</div><h4>{p.title}</h4>{p.translation && <p role="status">{p.translation.state === 'done' ? 'Переведено на русский' : p.translation.error || 'Ожидает перевода на русский; скрыто из ленты'}</p>}{!!p.media?.length && <small>Вложения: {p.media.length} · фото {p.media.filter(m => m.kind === 'photo').length}, видео {p.media.filter(m => m.kind === 'video').length}</small>}{p.mediaWarning && <p role="status">{p.mediaWarning}</p>}{p.summary && <p>{p.summary}</p>}<small>{p.hidden ? 'Скрыта из приложения' : p.translation?.state === 'pending' ? 'Ожидает перевода' : p.expiresAt && Date.parse(p.expiresAt) < Date.now() ? 'Срок действия истёк' : 'В приложении'} · {p.delivery?.state === 'sent' ? 'Отправлена в канал' : p.delivery ? 'Проверьте канал: результат отправки не подтверждён. Повтор автоматически не отправляется.' : 'В канал не отправлена'}</small><div className="on-actions">{p.url && <a href={p.url} target="_blank" rel="noopener noreferrer">Источник</a>}<button className="btn" disabled={busy} onClick={() => action('visibility', { id: p.id, hidden: !p.hidden }, p.hidden ? 'Публикация возвращена в ленту.' : 'Публикация скрыта из приложения. Отправленное сообщение в канале остаётся.')}>{p.hidden ? 'Показать' : 'Скрыть'}</button></div></article>)}</div>{!posts.length && <p className="vx-muted">Публикаций пока нет. Проверьте источники или добавьте собственный материал о Дананге.</p>}
    </section>
  </div>;
}
