import React, { useEffect, useMemo, useState } from "react";
import { apiGetMyRequests } from "../lib/api";

type Lang = "ru" | "en";
function getTg() { return (window as any).Telegram?.WebApp; }
const stateLabel = (lang: Lang): Record<string, string> => ({ in_progress: lang === "en" ? "In progress" : "В работе", done: lang === "en" ? "Done" : "Готова", canceled: lang === "en" ? "Rejected" : "Отклонена", new: lang === "en" ? "In progress" : "В работе" });
function shortId(id: string) { const s = String(id || ""); return s.length > 6 ? s.slice(-6) : s; }
function fmtDateTime(iso: string, lang: Lang) { try { const d = new Date(iso); if (!Number.isFinite(d.getTime())) return ""; return d.toLocaleString(lang === "en" ? "en-GB" : "ru-RU", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" }); } catch { return ""; } }
function methodLabel(m: string, lang: Lang) { const v = String(m || "").toLowerCase(); if (v === "cash") return lang === "en" ? "Cash" : "Наличные"; if (v === "transfer") return lang === "en" ? "Transfer" : "Перевод"; if (v === "atm") return lang === "en" ? "ATM" : "Банкомат"; if (v === "other") return lang === "en" ? "Other" : "Другое"; return m || "—"; }
export default function HistoryTab({ me, lang = "ru" }: any) { const isEn = lang === "en"; const tg = getTg(); const initData = tg?.initData || me?.initData || ""; const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(""); const [requests, setRequests] = useState<any[]>([]); async function load() { if (!initData) return; setLoading(true); setError(""); try { const r = await apiGetMyRequests(initData); if (!r?.ok) { setError(r?.error || (isEn ? "Error" : "Ошибка")); setRequests([]); return; } setRequests(Array.isArray(r.requests) ? r.requests : []); } finally { setLoading(false); } } useEffect(() => { if (!initData) return; load(); const id = window.setInterval(load, 12000); return () => window.clearInterval(id); }, [initData, isEn]); const list = useMemo(() => (requests || []).slice().sort((a, b) => String(b?.created_at).localeCompare(String(a?.created_at))), [requests]); if (!initData) return <div className="small">{isEn ? "Open this tab inside Telegram." : "Откройте вкладку «Моя история» внутри Telegram."}</div>; const labels = stateLabel(lang); return <div><div className="vx-head" style={{ alignItems: "center" }}><div><div className="h2 vx-m0">{isEn ? "Deals" : "Сделки"}</div><div className="vx-meta">{isEn ? "Your exchange requests" : "Ваши заявки на обмен"}</div></div><div className="row vx-rowWrap vx-gap6" style={{ justifyContent: "flex-end" }}><button type="button" className="btn vx-btnSm" onClick={load}>{isEn ? "Refresh" : "Обновить"}</button></div></div>{loading ? <div className="vx-help">{isEn ? "Loading…" : "Загрузка…"}</div> : null}{error ? <div className="vx-help">{error}</div> : null}<div className="vx-sp12" />{list.length === 0 && !loading ? <div className="small">{isEn ? "No deals yet." : "Пока нет сделок."}</div> : null}<div className="vx-reqList">{list.map((r) => { const st = String(r?.state || ""); const stNorm = st === "new" ? "in_progress" : st; const title = `${r?.sellCurrency} → ${r?.buyCurrency}`; const meta = `${fmtDateTime(String(r?.created_at || ""), lang)} • #${shortId(String(r?.id || ""))}`; const line1 = `${isEn ? "You give" : "Отдаёте"}: ${r?.sellAmount} ${r?.sellCurrency}`; const line2 = `${isEn ? "You get" : "Получаете"}: ${r?.buyAmount} ${r?.buyCurrency}`; const methods = `${methodLabel(String(r?.payMethod || ""), lang)} → ${methodLabel(String(r?.receiveMethod || ""), lang)}`; return <button key={String(r?.id)} type="button" className="vx-reqRow" onClick={() => { const msg = `${title}
${meta}

${line1}
${line2}
${isEn ? "Method" : "Способ"}: ${methods}
${isEn ? "Status" : "Статус"}: ${labels[stNorm] || stNorm}`; tg?.showAlert?.(msg); }}><div className="vx-reqTop"><div style={{ fontWeight: 950 }}>{title}</div><div className="vx-tag" style={{ whiteSpace: "nowrap" }}>{labels[stNorm] || stNorm}</div></div><div className="vx-muted" style={{ marginTop: 4 }}>{meta}</div><div className="small" style={{ marginTop: 6, opacity: 0.92 }}>{line1}</div><div className="small" style={{ marginTop: 2, opacity: 0.92 }}>{line2}</div></button>; })}</div></div>; }
